name: CI Pipeline

on:
  push:
    branches: ["master"]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # âœ… ADD THIS BLOCK RIGHT HERE
      - name: Run flake8
        run: |
          pip install flake8
          flake8 src

      - name: Set image version
        run: |
          Z=1
          X=$((GITHUB_RUN_NUMBER % 10))
          Y=$(( (GITHUB_RUN_NUMBER / 10) % 10 ))
          echo "IMAGE_TAG=$Z.$Y.$X" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/artiset-assignment:${{ env.IMAGE_TAG }} .

      - name: Run basic test
        run: |
          docker run -d -p 5000:5000 --name test_container ${{ secrets.DOCKERHUB_USERNAME }}/artiset-assignment:${{ env.IMAGE_TAG }}
          sleep 5
          chmod +x test.sh
          ./test.sh
